#!/bin/bash

canwork=0

if [ $# -eq 0 ]
then
  canwork=0
else
  canwork=1
fi

if [ $canwork -eq 0 ]
then
	printf "\033[1m\033[34m"
  printf "usage: calc.sh expression\033[0m\n"
else
	printf "\033[1m\033[31m"
 	./itop.out -s "$1" | ./eval.out -s
	printf "\033[0m"
fi
